### ISSUE TITLE
No se puede Instalar.

### ISSUE THREAD

**Issue by DreNs** [conekta/conekta_prestashop#40]
Buenas tardes, no se puede instalar el módulo, ya intenté comprimir la carpeta tal como dice "conektaprestashop" en .ZIP, .TAR, con 4 diferentes compresores de archivos y cuando intento subirlo, me sale que el formato no es válido. También intenté subiendolo via FTP y tampoco lo reconoce mi prestashop 1.7.1, utilizo PHP 7.0.

Gracias.

**Comment by eduardoconekta** [comment]
Pasos para instalar el archivo:
```
git clone git@github.com:conekta/conekta_prestashop.git
zip -r conekta_prestashop.zip conekta_prestashop
```
@DreNs

**Comment by DreNs** [comment]
Cloning into 'conekta_prestashop'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.



Me sale esto al intentarlo.

**Comment by eduardoconekta** [comment]
prueba haciendolo con el resource https, si no mal recuerdo eso pide tu usuario y contraseña
```
git clone https://github.com/conekta/conekta_prestashop.git
```
Tienes dada de alta esa pc en github ? 
es decir ligada a las llaves RSA ?

**Comment by eduardoconekta** [comment]
O la solución definitiva es bajar el zip con el formato
 `conekta_prestashop-master.zip`
descomprimirlo y quedara la carpeta
`conekta_prestashop-master`
seguido de eso renombrar la carpeta 
`mv conekta_prestashop-master conekta_prestashop`
y por ultimo  comprimirlo
`zip -r conekta_prestashop.zip conekta_prestashop`

pero se me hace muy raro que no puedas bajar el repo, ya hemos tenido un cliente que nos indico que lo instalo sin problemas 
te explico, prestashop no admite guiones intermedios en el nombre de los plugins es por eso que si bajas el release o master no podrás instalar directamente el plugin ya que el release tiene al final la version del plugin (-1.0.0) y master tiene el guion (-master) es por eso que causa conflictos

**Comment by eduardoconekta** [comment]
Un webhook es un listener siempre activo que tu provees para que tus ordenes escuchen los eventos que nosotros mandamos a su sitio como el evento en que una orden se paga y esta se actualice automaticamente en tu dashboard, debes de registrar uno en ese campo que seria la url de tu dominio mas la ruta donde esta alojado tu codigo, puedes leer mas sobre eso en https://developers.conekta.com/resources/webhooks

**Comment by DreNs** [comment]
Perfecto, muchas gracias. Investigaré sobre el tema, una ultima pregunta, estoy intentado pagar con datos falsos para ver las validaciones y con todo tipo de intentos me sale el error HTTP 500, reviso el error_log de prestashop y me aparece lo siguiente. Disculpa las molestias por tantas preguntas.



[21-Aug-2017 11:35:55 America/Mexico_City] PHP Notice:  Undefined variable: total in /home/danielfuentes/public_html/modules/conekta_prestashop/conekta_prestashop.php on line 900
[21-Aug-2017 11:36:09 America/Mexico_City] PHP Deprecated:  Non-static method Config::getLineItems() should not be called statically in /home/danielfuentes/public_html/modules/conekta_prestashop/conekta_prestashop.php on line 940
[21-Aug-2017 11:36:09 America/Mexico_City] PHP Deprecated:  Non-static method Config::getTaxLines() should not be called statically in /home/danielfuentes/public_html/modules/conekta_prestashop/conekta_prestashop.php on line 941
[21-Aug-2017 11:36:09 America/Mexico_City] PHP Deprecated:  Non-static method Config::getDiscountLines() should not be called statically in /home/danielfuentes/public_html/modules/conekta_prestashop/conekta_prestashop.php on line 942
[21-Aug-2017 11:36:09 America/Mexico_City] PHP Deprecated:  Non-static method Config::getCustomerInfo() should not be called statically in /home/danielfuentes/public_html/modules/conekta_prestashop/conekta_prestashop.php on line 943
[21-Aug-2017 11:36:09 America/Mexico_City] PHP Deprecated:  Non-static method Config::getShippingLines() should not be called statically in /home/danielfuentes/public_html/modules/conekta_prestashop/conekta_prestashop.php on line 944
[21-Aug-2017 11:36:09 America/Mexico_City] PHP Deprecated:  Non-static method Config::getShippingContact() should not be called statically in /home/danielfuentes/public_html/modules/conekta_prestashop/conekta_prestashop.php on line 949
[21-Aug-2017 11:36:10 America/Mexico_City] PHP Fatal error:  Uncaught Conekta\ParameterValidationError: El token no existe. in /home/danielfuentes/public_html/modules/conekta_prestashop/lib/conekta-php/lib/Conekta/Exceptions/Handler.php:82
Stack trace:
#0 /home/danielfuentes/public_html/modules/conekta_prestashop/lib/conekta-php/lib/Conekta/Exceptions/Handler.php(96): Conekta\Handler::build(Array, 422)
#1 /home/danielfuentes/public_html/modules/conekta_prestashop/lib/conekta-php/lib/Conekta/Requestor.php(107): Conekta\Handler::errorHandler(Array, 422)
#2 /home/danielfuentes/public_html/modules/conekta_prestashop/lib/conekta-php/lib/Conekta/Resource.php(149): Conekta\Requestor->request('post', 'https://api.con...', Array)
#3 /home/danielfuentes/public_html/modules/conekta_prestashop/lib/conekta-php/lib/Conekta/Order.php(110): Conekta\Resource->_createMember('charges', Array)
#4 /home/danielfuentes/public_html/modules/conekta_prestashop/conekta_prestashop.php(1042): Conekta\Order->createCharge(Array)
#5 /home/danielfuentes/public_html/modules/conekta_prestashop/controlle in /home/danielfuentes/public_html/modules/conekta_prestashop/lib/conekta-php/lib/Conekta/Exceptions/Handler.php on line 82

**Comment by eduardoconekta** [comment]
Ok, eso si esta raro, nos puedes poner la siguiente informacion? 
PHP version
Prestashop version
Tienes ya seteadas tus credenciales de prueba en el plugin ?

**Comment by DreNs** [comment]
Tengo la versión 1.7.1.2, y la versión de PHP es la 7.0. Eduardo, si gustas puedo darte acceso remoto a mi PC para acceso completo   o podemos hablar por teléfono, te dejo mi correo si podemos establecer contacto. Danielfuentes@live.com  Disculpa tanta insistencia; lo qué pasa es que me urge tener funcionando el módulo con ustedes para poder lanzar mi sitio.

**Comment by eduardoconekta** [comment]
para tener soporte te recomiendo mandar un correo a soporte@conekta.com ellos te podrán ayudar con todas tus dudas sin costo (: @DreNs
